# Generated by Django 5.0.3 on 2024-03-19 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('convos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvoMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('type', models.CharField(choices=[('user', 'User'), ('system', 'System')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField()),
                ('convo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convos.convos')),
            ],
        ),
    ]
