# Generated by Django 5.0.3 on 2024-03-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convo_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convomessages',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
